blank_issues_enabled: false
contact_links:
  - name: Questions / usage help
    url: https://github.com/selberhad/chatgpt-export-viewer/discussions
    about: Ask questions and share tips in Discussions.

